config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:new, :show, :create]
  root 'homes#top'
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user   #ヘルパーメソッドを定義する事でヴューで使用できる
  def Login?    #ログインしているか判定するメソッド
    if current_user.nil?  #カレントユーザーがニルという事はログイン出来ていない
      redirect_to login_path, alert: "You have to log in."
    end  
  end
  
  def already_login?    #もうログインしているならログイン画面や新規登録画面に活きたくない　ログインしているならマイページに遷移する
    unless current_user.nil?
      redirect_to user_path, notice: "You are already logged in."
    end  
  end  
  
  def current_user     #このカレントユーザーというメソッドはログインしている人の情報を取ってくるメソッド
    if session[:user_id]  #session[:user_id]に何かしら値が入っていれば下のアクションを実行する
      current_user ||= User.find(session[:user_id]) #カレントユーザーがニルでなかったら右側の値を入れる
    end                                             #ニルでなければ最終的にカレントユーザというメソッドにデータが入る
  end  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_login?, except: :destroy
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path, notice: "You have successfully logged in."
    else
      flash.now[:alert] = "Email or Password is invalid."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have successfully logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_login?, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path, notice: "You have successfully logged in."
    else
      reder :new
    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>Hello!</h1>

<%= link_to "Sign up", new_user_path %>
<%= link_to "Login", login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with model: @user, url: user_path, local: true do |f| %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit "Sign up" %>
  </div>
  <%= link_to "Login" , login_path %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome!</h1>
<p>You are logged in as "<strong><%= current_user.email %>.</strong>"</p>
<%= link_to "Logout" ,  logout_path, method: :delete %>